language: csharp
dist: xenial
mono: none
dotnet: 2.1
script:
 - export APP_PROJECT_NAME=Checkout.Api
 - export TEST_PROJECT_NAME=Checkout.Api
 - dotnet restore
 - dotnet build
 - dotnet test $TEST_PROJECT_NAME --filter "TestCategory!=ThirdParty"